version: "3"
services:
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        networks:
            - my-network

    backend:
        build: ./backend
        ports:
            - "3001:3001"
        networks:
            - my-network

    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - "80:80"
        depends_on:
            - frontend
            - backend
        networks:
            - my-network

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        networks:
            - my-network

networks:
    my-network:
        external: true
