version: "3"
services:
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        networks:
            - my-network

    backend:
        build: ./backend
        ports:
            - "3001:3001"
        volumes:
            - ./backend:/app
            - /app/node_modules
        environment:
            - DATABASE_URL=mysql://user:password@db:3306/mydatabase
        networks:
            - my-network

    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - "80:80"
        depends_on:
            - frontend
            - backend
        networks:
            - my-network

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        networks:
            - my-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - my-network

networks:
    my-network:
        driver: bridge
